%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.7

-ifndef(prometheus_model).
-define(prometheus_model, true).

-define(prometheus_model_gpb_version, "4.21.7").


-ifndef('LABELPAIR_PB_H').
-define('LABELPAIR_PB_H', true).
-record('LabelPair',
        {name                   :: unicode:chardata() | undefined, % = 1, optional
         value                  :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('GAUGE_PB_H').
-define('GAUGE_PB_H', true).
-record('Gauge',
        {value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('COUNTER_PB_H').
-define('COUNTER_PB_H', true).
-record('Counter',
        {value                  :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1, optional
         exemplar               :: prometheus_model:'Exemplar'() | undefined, % = 2, optional
         created_timestamp      :: prometheus_model:'Timestamp'() | undefined % = 3, optional
        }).
-endif.

-ifndef('QUANTILE_PB_H').
-define('QUANTILE_PB_H', true).
-record('Quantile',
        {quantile               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1, optional
         value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2, optional
        }).
-endif.

-ifndef('SUMMARY_PB_H').
-define('SUMMARY_PB_H', true).
-record('Summary',
        {sample_count           :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         sample_sum             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         quantile = []          :: [prometheus_model:'Quantile'()] | undefined, % = 3, repeated
         created_timestamp      :: prometheus_model:'Timestamp'() | undefined % = 4, optional
        }).
-endif.

-ifndef('UNTYPED_PB_H').
-define('UNTYPED_PB_H', true).
-record('Untyped',
        {value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('HISTOGRAM_PB_H').
-define('HISTOGRAM_PB_H', true).
-record('Histogram',
        {sample_count           :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         sample_count_float     :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4, optional
         sample_sum             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         bucket = []            :: [prometheus_model:'Bucket'()] | undefined, % = 3, repeated
         created_timestamp      :: prometheus_model:'Timestamp'() | undefined, % = 15, optional
         schema                 :: integer() | undefined, % = 5, optional, 32 bits
         zero_threshold         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6, optional
         zero_count             :: non_neg_integer() | undefined, % = 7, optional, 64 bits
         zero_count_float       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 8, optional
         negative_span = []     :: [prometheus_model:'BucketSpan'()] | undefined, % = 9, repeated
         negative_delta = []    :: [integer()] | undefined, % = 10, repeated, 64 bits
         negative_count = []    :: [float() | integer() | infinity | '-infinity' | nan] | undefined, % = 11, repeated
         positive_span = []     :: [prometheus_model:'BucketSpan'()] | undefined, % = 12, repeated
         positive_delta = []    :: [integer()] | undefined, % = 13, repeated, 64 bits
         positive_count = []    :: [float() | integer() | infinity | '-infinity' | nan] | undefined, % = 14, repeated
         exemplars = []         :: [prometheus_model:'Exemplar'()] | undefined % = 16, repeated
        }).
-endif.

-ifndef('BUCKET_PB_H').
-define('BUCKET_PB_H', true).
-record('Bucket',
        {cumulative_count       :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         cumulative_count_float :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4, optional
         upper_bound            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         exemplar               :: prometheus_model:'Exemplar'() | undefined % = 3, optional
        }).
-endif.

-ifndef('BUCKETSPAN_PB_H').
-define('BUCKETSPAN_PB_H', true).
-record('BucketSpan',
        {offset                 :: integer() | undefined, % = 1, optional, 32 bits
         length                 :: non_neg_integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-ifndef('EXEMPLAR_PB_H').
-define('EXEMPLAR_PB_H', true).
-record('Exemplar',
        {label = []             :: [prometheus_model:'LabelPair'()] | undefined, % = 1, repeated
         value                  :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         timestamp              :: prometheus_model:'Timestamp'() | undefined % = 3, optional
        }).
-endif.

-ifndef('METRIC_PB_H').
-define('METRIC_PB_H', true).
-record('Metric',
        {label = []             :: [prometheus_model:'LabelPair'()] | undefined, % = 1, repeated
         gauge                  :: prometheus_model:'Gauge'() | undefined, % = 2, optional
         counter                :: prometheus_model:'Counter'() | undefined, % = 3, optional
         summary                :: prometheus_model:'Summary'() | undefined, % = 4, optional
         untyped                :: prometheus_model:'Untyped'() | undefined, % = 5, optional
         histogram              :: prometheus_model:'Histogram'() | undefined, % = 7, optional
         timestamp_ms           :: integer() | undefined % = 6, optional, 64 bits
        }).
-endif.

-ifndef('METRICFAMILY_PB_H').
-define('METRICFAMILY_PB_H', true).
-record('MetricFamily',
        {name                   :: unicode:chardata() | undefined, % = 1, optional
         help                   :: unicode:chardata() | undefined, % = 2, optional
         type                   :: 'COUNTER' | 'GAUGE' | 'SUMMARY' | 'UNTYPED' | 'HISTOGRAM' | 'GAUGE_HISTOGRAM' | integer() | undefined, % = 3, optional, enum io.prometheus.client.MetricType
         metric = []            :: [prometheus_model:'Metric'()] | undefined, % = 4, repeated
         unit                   :: unicode:chardata() | undefined % = 5, optional
        }).
-endif.

-ifndef('TIMESTAMP_PB_H').
-define('TIMESTAMP_PB_H', true).
-record('Timestamp',
        {seconds = 0            :: integer() | undefined, % = 1, optional, 64 bits
         nanos = 0              :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-endif.
