%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.6.0

-ifndef(prometheus_model).
-define(prometheus_model, true).

-define(prometheus_model_gpb_version, "4.6.0").

-ifndef('LABELPAIR_PB_H').
-define('LABELPAIR_PB_H', true).
-record('LabelPair',
    % = 1
    {
        name :: iodata() | undefined,
        % = 2
        value :: iodata() | undefined
    }
).
-endif.

-ifndef('GAUGE_PB_H').
-define('GAUGE_PB_H', true).
-record('Gauge',
    % = 1
    {value :: float() | integer() | infinity | '-infinity' | nan | undefined}
).
-endif.

-ifndef('COUNTER_PB_H').
-define('COUNTER_PB_H', true).
-record('Counter',
    % = 1
    {value :: float() | integer() | infinity | '-infinity' | nan | undefined}
).
-endif.

-ifndef('QUANTILE_PB_H').
-define('QUANTILE_PB_H', true).
-record('Quantile',
    % = 1
    {
        quantile :: float() | integer() | infinity | '-infinity' | nan | undefined,
        % = 2
        value :: float() | integer() | infinity | '-infinity' | nan | undefined
    }
).
-endif.

-ifndef('SUMMARY_PB_H').
-define('SUMMARY_PB_H', true).
-record('Summary',
    % = 1, 32 bits
    {
        sample_count :: non_neg_integer() | undefined,
        % = 2
        sample_sum :: float() | integer() | infinity | '-infinity' | nan | undefined,
        % = 3
        quantile = [] :: [prometheus_model:'Quantile'()] | undefined
    }
).
-endif.

-ifndef('UNTYPED_PB_H').
-define('UNTYPED_PB_H', true).
-record('Untyped',
    % = 1
    {value :: float() | integer() | infinity | '-infinity' | nan | undefined}
).
-endif.

-ifndef('HISTOGRAM_PB_H').
-define('HISTOGRAM_PB_H', true).
-record('Histogram',
    % = 1, 32 bits
    {
        sample_count :: non_neg_integer() | undefined,
        % = 2
        sample_sum :: float() | integer() | infinity | '-infinity' | nan | undefined,
        % = 3
        bucket = [] :: [prometheus_model:'Bucket'()] | undefined
    }
).
-endif.

-ifndef('BUCKET_PB_H').
-define('BUCKET_PB_H', true).
-record('Bucket',
    % = 1, 32 bits
    {
        cumulative_count :: non_neg_integer() | undefined,
        % = 2
        upper_bound :: float() | integer() | infinity | '-infinity' | nan | undefined
    }
).
-endif.

-ifndef('METRIC_PB_H').
-define('METRIC_PB_H', true).
-record('Metric',
    % = 1
    {
        label = [] :: [prometheus_model:'LabelPair'()] | undefined,
        % = 2
        gauge :: prometheus_model:'Gauge'() | undefined,
        % = 3
        counter :: prometheus_model:'Counter'() | undefined,
        % = 4
        summary :: prometheus_model:'Summary'() | undefined,
        % = 5
        untyped :: prometheus_model:'Untyped'() | undefined,
        % = 7
        histogram :: prometheus_model:'Histogram'() | undefined,
        % = 6, 32 bits
        timestamp_ms :: integer() | undefined
    }
).
-endif.

-ifndef('METRICFAMILY_PB_H').
-define('METRICFAMILY_PB_H', true).
-record('MetricFamily',
    % = 1
    {
        name :: iodata() | undefined,
        % = 2
        help :: iodata() | undefined,
        % = 3, enum MetricType
        type :: 'COUNTER' | 'GAUGE' | 'SUMMARY' | 'UNTYPED' | 'HISTOGRAM' | integer() | undefined,
        % = 4
        metric = [] :: [prometheus_model:'Metric'()] | undefined
    }
).
-endif.

-endif.
