name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['28', '27', '26']
        rebar3: ['3.24']
    runs-on: 'ubuntu-24.04'
    env:
      OTPVER: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 compile
      - run: rebar3 lint
      - run: rebar3 xref
      - run: rebar3 dialyzer
      - run: rebar3 eunit
      - run: rebar3 fmt --check
        if: ${{ matrix.otp == '28' }}
      - run: rebar3 ex_doc
        if: ${{ matrix.otp == '28' }}
      - run: rebar3 do cover, covertool generate
        if: ${{ matrix.otp == '28' }}
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        if: ${{ matrix.otp == '28' }}
        with:
          files: _build/test/covertool/prometheus.covertool.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
